Repository codestates-beb/BEB-07-final-entasis, pull requests merged in 2023-02, with the labels that each got.

#136 Chart Edited
  client/src/components/Chart/Chart.js
  client/src/components/Chart/ChartWrapper.js
  client/src/pages/MainPage.js
Labels: enhancement

#137 edit : TransactionPage
  client/src/pages/TransactionsPage.js
Labels: enhancement

#138 edit : refresh connection
  client/.env
  client/src/components/Header.js
Labels: enhancement

#141 Chart & CSS
  client/src/assets/css/main.css
  client/src/components/Chart/Chart.js
  client/src/components/Chart/ChartWrapper.js
  client/src/components/Chart/data/Candle.js
  server/src/app.js
Labels: enhancement

#144 Changes
  client/src/assets/css/main.css
  client/src/components/Chart/Chart.js
  client/src/components/Chart/ChartWrapper.js
  client/src/components/Footer.js
  client/src/components/Navigator.js
  client/src/pages/MainPage.js
  server/src/app.js
  server/src/models/dividend_his.js
  server/src/routes/userRouter.js
Labels: enhancement

#147 Some
  client/src/assets/css/main.css
  client/src/components/Chart/Chart.js
  client/src/components/Chart/ChartWrapper.js
  client/src/components/Chart/data/Candle.js
  client/src/components/Chart/data/Volume.js
  client/src/components/History.js
  client/src/components/Historys.js
  client/src/pages/MainPage.js
  server/src/app.js
Labels: enhancement

#149 Some
  client/src/assets/css/main.css
  client/src/components/Assets.js
  client/src/components/Header.js
  client/src/components/History.js
  client/src/components/Historys.js
  client/src/components/Order.js
  client/src/pages/MainPage.js
  server/src/app.js
Labels: enhancement

#151 Edit : front API, Update Contract
  client/.env
  client/src/ABIs/ERC1400.json
  client/src/ABIs/ERC1400Interface.json
  client/src/ABIs/OwnerHelper.json
  client/src/apis/token.js
  client/src/components/Assets.js
  client/src/components/Order.js
  client/src/pages/MainPage.js
Labels: enhancement

#152 Main
  client/src/assets/css/main.css
  client/src/assets/images/chart_tutorials.webp
  client/src/assets/images/danger.png
  client/src/components/Assets.js
  client/src/components/Chart/Chart.js
  client/src/components/Chart/ChartWrapper.js
  client/src/components/Footer.js
  client/src/components/Navigator.js
  client/src/components/Order.js
  client/src/components/Tutorials.js
  client/src/pages/MainPage.js
Labels: enhancement

#162 Edit set
  client/src/App.js
  client/src/components/Chart/Chart.js
  client/src/components/Chart/data/Candle.js
  client/src/components/History.js
  client/src/pages/MainPage.js
  client/src/pages/TransactionsPage.js
  server/src/app.js
Labels: bug, enhancement

#166 Some
  client/src/assets/css/main.css
  client/src/components/Chart/ChartWrapper.js
  client/src/components/Chart/data/Candle.js
  client/src/components/Header.js
  client/src/components/Historys.js
  client/src/components/Order.js
  client/src/components/Tutorials.js
  client/src/pages/MainPage.js
  server/src/app.js
Labels: bug

#172 Change
  client/src/assets/css/main.css
  client/src/components/Chart/ChartWrapper.js
  client/src/components/Historys.js
  client/src/pages/MainPage.js
Labels: documentation, enhancement

#173 Transaction Page
  client/src/App.js
  client/src/assets/css/main.css
  client/src/components/History.js
  client/src/components/Historys.js
  client/src/pages/MainPage.js
  client/src/pages/TransactionsPage.js
Labels: enhancement

#176 Footer & Welcome Page Link
  client/src/App.js
  client/src/assets/css/main.css
  client/src/components/Footer.js
  client/src/pages/MainPage.js
  client/src/pages/TransactionsPage.js
  client/src/pages/WelcomePage.js
Labels: enhancement

#178 Transactions & History Connections
  client/src/assets/css/main.css
  client/src/components/Header.js
  client/src/components/History.js
  client/src/components/Historys.js
  client/src/components/Order.js
  client/src/pages/MainPage.js
  client/src/pages/TransactionsPage.js
  client/src/pages/WelcomePage.js
Labels: documentation, enhancement

#186 Public Disclosure Setting
  client/src/assets/css/main.css
  client/src/components/Chart/data/Volume.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/PublicDisclosure.js
  client/src/pages/MainPage.js
Labels: documentation, enhancement

#192 Nav
  client/src/assets/css/main.css
  client/src/components/Assets.js
  client/src/components/Historys.js
  client/src/components/Navigator.js
  server/src/models/position_his.js
Labels: enhancement

#195 Footer
  client/src/assets/css/main.css
  client/src/assets/images/footer_img.jpeg
  client/src/components/Chart/Chart.js
  client/src/components/Footer.js
  client/src/components/Historys.js
  client/src/components/Order.js
Labels: enhancement

#200 Order
  client/src/components/Chart/ChartWrapper.js
  client/src/components/Chart/data/Candle.js
  client/src/components/History.js
  client/src/components/Historys.js
  client/src/components/Order.js
  server/src/app.js
Labels: enhancement

#205 Changes
  client/src/components/Assets.js
  client/src/components/Chart/ChartWrapper.js
  client/src/components/Header.js
  client/src/components/Historys.js
  client/src/components/Navigator.js
  client/src/components/Order.js
  client/src/pages/MainPage.js
Labels: bug, duplicate, enhancement

#206 Address
  client/src/pages/MainPage.js
Labels: bug

#208 CORS
  server/src/app.js
Labels: bug

#211 Transactions Page
  client/src/App.js
  client/src/assets/css/main.css
  client/src/components/Chart/Chart.js
  client/src/components/Chart/ChartWrapper.js
  client/src/components/Header.js
  client/src/components/Navigator.js
  client/src/components/Order.js
  client/src/components/Select.js
  client/src/pages/MainPage.js
  client/src/pages/TransactionsPage.js
Labels: enhancement

#212 Error Resolved
  client/src/ABIs/ERC1400.json
  client/src/ABIs/ERC1400Interface.json
  client/src/ABIs/OwnerHelper.json
  client/src/App.js
  client/src/assets/css/main.css
  client/src/components/Header.js
  client/src/components/Historys.js
  client/src/components/Order.js
  client/src/pages/MainPage.js
Labels: bug, enhancement

#213 Global
  client/src/components/Navigator.js
Labels: enhancement

#214 Change
  client/src/App.js
  client/src/apis/chart.js
  client/src/apis/company.js
  client/src/apis/token.js
  client/src/apis/user.js
  client/src/assets/css/main.css
  client/src/components/Chart/data/Candle.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/Order.js
  client/src/pages/MainPage.js
  client/src/pages/TransactionsPage.js
Labels: bug, enhancement

#217 Change
  client/src/App.js
  client/src/apis/chart.js
  client/src/apis/company.js
  client/src/apis/token.js
  client/src/apis/user.js
  client/src/assets/css/main.css
  client/src/components/Header.js
  client/src/components/Navigator.js
  client/src/components/Tutorials.js
  client/src/pages/MainPage.js
Labels: enhancement

#218 Address
  client/src/apis/chart.js
  client/src/apis/company.js
  client/src/apis/token.js
  client/src/apis/user.js
  client/src/pages/MainPage.js
Labels: bug

#219 edit : Translation
  client/src/components/Assets.js
  client/src/components/Header.js
  client/src/components/History.js
  client/src/components/Historys.js
  client/src/components/LimitOrderBook.js
  client/src/components/Navigator.js
  client/src/components/Order.js
  client/src/lang/lang.en.json
  client/src/lang/lang.ko.json
Labels: enhancement

#223 Tutorial
  client/src/App.js
  client/src/assets/css/main.css
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/Historys.js
  client/src/components/Navigator.js
  client/src/components/Tutorials.js
  client/src/pages/MainPage.js
  client/src/pages/TransactionsPage.js
  server/src/app.js
Labels: enhancement

#227 Tutorial
  client/src/components/Tutorials.js
Labels: bug

#228 Tutorial
  client/src/assets/css/main.css
  client/src/assets/images/bitcoin.jpeg
  client/src/assets/images/ethers.webp
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/Navigator.js
  client/src/components/Order.js
  client/src/components/Tutorials.js
  client/src/pages/MainPage.js
Labels: enhancement

#234 Tutorial
  client/src/App.js
  client/src/components/Footer.js
  client/src/components/Navigator.js
  client/src/components/Tutorials.js
Labels: bug
